# Generated by Django 4.1.7 on 2023-03-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='auto',
            name='marca',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='auto',
            name='modelo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auto',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
